{
 "title": "Gardiyantest",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top Application",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"proto\")  \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  \r\n  |> group(columns: [\"proto\"])  \r\n  |> sum(column: \"bytes\")  \r\n  |> rename(columns: {bytes: \"\"})  \r\n  |> sort(columns: [\"\"], desc: true)  \r\n  |> yield(name: \"top_app_traffic\")\r\n"
    }
   ]
  },
  {
   "title": "All Traffic",
   "type": "stat",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"packets\" or r[\"_field\"] == \"flows\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n        _time: r._time,\r\n        bps: (float(v: r.bytes) * 8.0) / (float(v: int(v: v.windowPeriod)) / 1000000000.0),\r\n        pps: float(v: r.packets) / (float(v: int(v: v.windowPeriod)) / 1000000000.0),\r\n        fps: float(v: r.flows) / (float(v: int(v: v.windowPeriod)) / 1000000000.0)\r\n  }))\r\n  |> yield(name: \"all_traffic\")\r\n"
    }
   ]
  },
  {
   "title": "Top Source (Host)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"src_addr\")  \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  \r\n  |> group(columns: [\"src_addr\"])  \r\n  |> sum(column: \"bytes\")  \r\n  |> rename(columns: {bytes: \"\"})  \r\n  |> sort(columns: [\"\"], desc: true)  \r\n  |> yield(name: \"top_traffic_sources\")\r\n"
    }
   ]
  },
  {
   "title": "Bytes - Packet",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets\" or r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"icmp_code\")\r\n  |> unique()\r\n  |> yield(name: \"unique\")\r\n\r\nfrom(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets\" or r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"icmp_code\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n\r\nfrom(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets\" or r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"icmp_code\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false)\r\n  |> yield(name: \"first\")"
    }
   ]
  },
  {
   "title": "Top Source (PORT)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"src_port\")  \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  \r\n  |> group(columns: [\"src_port\"])  \r\n  |> sum(column: \"bytes\")  \r\n  |> rename(columns: {bytes: \"Port:\"})  \r\n  |> sort(columns: [\"total_bytes\"], desc: true)  \r\n  |> limit(n: 10)  \r\n  |> yield(name: \"top_source_ports\")\r\n"
    }
   ]
  },
  {
   "title": "Top Destination (HOST)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"dst_addr\")  \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  \r\n  |> group(columns: [\"dst_addr\"])  \r\n  |> sum(column: \"bytes\")  \r\n  |> rename(columns: {bytes: \"\"})  \r\n  |> sort(columns: [\"\"], desc: true)  \r\n  |> limit(n: 10)  \r\n  |> yield(name: \"top_destination_traffic\")\r\n"
    }
   ]
  },
  {
   "title": "Top Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_if\" or r[\"_field\"] == \"out_if\" or r[\"_field\"] == \"bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Top Destination (PORT)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"dst_port\")  \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  \r\n  |> group(columns: [\"dst_port\"])  \r\n  |> sum(column: \"bytes\")  \r\n  |> rename(columns: {bytes: \"\"})  \r\n  |> sort(columns: [\" \"], desc: true)  \r\n  |> limit(n: 10)  \r\n  |> yield(name: \"top_destination_ports\")\r\n"
    }
   ]
  },
  {
   "title": "Trafic Panel",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"src_addr\" or r[\"_field\"] == \"dst_port\" or r[\"_field\"] == \"dst_addr\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"src_addr\", \"dst_port\", \"dst_addr\"])\r\n  |> sum(column: \"bytes\")\r\n  |> map(fn: (r) => ({\r\n        source: r.src_addr,\r\n    service:\r\n          if r.dst_port == 80 then \"HTTP\"\r\n          else if r.dst_port == 443 then \"HTTPS\"\r\n          else if r.dst_port == 8080 then \"HTTP-Alt\"\r\n          else if r.dst_port == 8443 then \"HTTPS-Alt\"\r\n          else if r.dst_port == 53 then \"DNS\"\r\n          else if r.dst_port == 25 then \"SMTP\"\r\n          else if r.dst_port == 587 then \"SMTP-Submission\"\r\n          else if r.dst_port == 465 then \"SMTPS\"\r\n          else if r.dst_port == 110 then \"POP3\"\r\n          else if r.dst_port == 995 then \"POP3-SSL\"\r\n          else if r.dst_port == 22 then \"SSH\"\r\n          else if r.dst_port == 21 then \"FTP\"\r\n          else if r.dst_port == 23 then \"Telnet\"\r\n          else if r.dst_port == 161 then \"SNMP\"\r\n          else if r.dst_port == 3389 then \"RDP\"\r\n          else if r.dst_port == 3306 then \"MySQL\"\r\n          else if r.dst_port == 1433 then \"MSSQL\"\r\n          else if r.dst_port == 1521 then \"Oracle DB\"\r\n          else if r.dst_port == 6379 then \"Redis\"\r\n          else if r.dst_port == 993 then \"IMAP-SSL\"\r\n          else if r.dst_port == 143 then \"IMAP\"\r\n          else \"Other\",\r\n        target: r.dst_addr,\r\n        total_bytes: r.bytes\r\n  }))\r\n  |> yield(name: \"sankey_data\")\r\n"
    }
   ]
  },
  {
   "title": "Top Conversation",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"src_addr\" or r[\"_field\"] == \"dst_addr\" or r[\"_field\"] == \"dst_port\" or r[\"_field\"] == \"bytes\")\r\n  |> map(fn: (r) => ({ r with _value: string(v: r._value) }))  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") \r\n  |> map(fn: (r) => ({\r\n        _time: r._time,\r\n        Source: r.src_addr,\r\n        Destination: r.dst_addr,\r\n        Application: if exists r.dst_port and int(v: r.dst_port) == 80 then \"HTTP\"\r\n                     else if exists r.dst_port and int(v: r.dst_port) == 443 then \"HTTPS\"\r\n                     else if exists r.dst_port and int(v: r.dst_port) == 110 then \"POP3\"\r\n                     else if exists r.dst_port and int(v: r.dst_port) == 500 then \"IPSec\"\r\n                     else \"Unknown\",\r\n        Traffic_Bytes: if exists r.bytes then float(v: r.bytes) else 0.0\r\n  }))\r\n  |> yield(name: \"top_conversations\")\r\n"
    }
   ]
  },
  {
   "title": "Last_NetFlow_Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flows\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"src_addr\" or r[\"_field\"] == \"src_port\" or r[\"_field\"] == \"dst_addr\" or r[\"_field\"] == \"dst_port\")\r\n  |> map(fn: (r) => ({ r with _value: string(v: r._value) }))  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") \r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  }
 ]
}