services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
      - "--storage.tsdb.retention.size=10GB"
      - "--storage.tsdb.wal-compression"  
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - portainer_data:/data  
    environment:
      TZ: "Europe/Istanbul"
 
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5    
  telegraf:
    image: telegraf:1.34.1
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
  kapacitor:
    image: kapacitor:1.6
    container_name: kapacitor
    ports:
      - "9092:9092"
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf
      - ./kapacitor_data:/var/lib/kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=admin
      - KAPACITOR_INFLUXDB_0_PASSWORD=admin123
      - KAPACITOR_INFLUXDB_0_INFLUXDBVERSION=2
      - KAPACITOR_INFLUXDB_0_TOKEN=YY_NE0RWwiw1KIEPql46Gne-cjxEzau189im5-Tbuq3RiEooZh_C4A93Rbz4xg_la4_eqlO98wHV05KCQYhIrA==
      - KAPACITOR_INFLUXDB_0_ORG=gardiyan
      - KAPACITOR_INFLUXDB_0_BUCKET=vmware
    depends_on:
      - influxdb

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

  karma:
    image: lmierzwa/karma:latest
    container_name: karma
    ports:
      - "8080:8080"
    environment:
      - ALERTMANAGER_URI=http://alertmanager:9093
    depends_on:
      - alertmanager
volumes:
  grafana-data:
  portainer_data:
  prometheus_data:  
