services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /mnt/docker/homepage/config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock  
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=localhost:3000,0.0.0.0:3000,127.0.0.1:3000,172.16.18.110:3000  
