services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/cekino.crt:/etc/nginx/ssl/cekino.crt:ro
      - ./ssl/cekino.rsa:/etc/nginx/ssl/cekino.rsa:ro
    ports:
      - "443:443"  
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
