services:
  sonarqube:
    image: sonarqube:lts-community
    hostname: sonarqube
    container_name: sonarqube
    # read_only: true
    depends_on:
      sonarqube_db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonar_volume/sonarqube_data:/opt/sonarqube/data
      - ./sonar_volume/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonar_volume/sonarqube_logs:/opt/sonarqube/logs
      - ./sonar_volume/sonarqube_temp:/opt/sonarqube/temp
    ports:
      - "9000:9000"
    restart: unless-stopped

  sonarqube_db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      #- postgresql:/var/lib/postgresql
      - /mnt/docker/app2/sonarqube/data/posgre_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgresql:
