#
# NETDISCO 2 CONFIGURATION FILE
#
# Settings in this file override share/config.yml
#
# https://github.com/netdisco/netdisco/wiki/Configuration has
# in depth explanations about each setting.

# ------------------
# ESSENTIAL SETTINGS
# ------------------

database:
  name: 'karcin_network'
  user: 'postgres'
  pass: 'Cekino.123!'
  host: 'db'

# ------------------------
# DOCKER SPECIFIC SETTINGS
# ------------------------

# Allows you to put plugin code in /lib, and templates in /share/views,
# within the nd-site-local directory.
site_local_files: true

# set to true to globally disable authentication/login.
# the user called "guest" has full admin/port-control rights.
# this user will be created by default on your first deploy.
no_auth: true

# --------------------
# RECOMMENDED SETTINGS
# --------------------

# Device authentication settings
# define snmp communities and ssh credentials here
# ````````````````````````````````````````````````
device_auth:
  - tag: 'default_v2_readonly'
    community: 'public'
    read: true
    write: false
#  - tag: 'default_v2_for_write'
#    community: 'private'
#    read: false
#    write: true



# will be stripped from fqdn when displayed in the web UI
# also, do not forget the leading dot.
# ```````````````````````````````````````````````````````
#domain_suffix: ['.example.com']


# ¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸
# ¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸.·´¯`·.¸¸


# ---------------------------------------------------------------
# OTHER INTERESTING SETTINGS WHERE THE DEFAULTS ARE PROBABLY OKAY
# ---------------------------------------------------------------

# discover Wireless Access Points, but not IP Phones
# usually these are visible as device neighbors but don't support
# SNMP, which just clogs up the job queue.
# ```````````````````````````````````````````````````````````````
#discover_waps: true
#discover_phones: false

# this is the schedule for automatically keeping netdisco up-to-date;
# these are good defaults, so only uncomment if needing to change.
# (or set "schedule: null" if you wish to disable the scheduler)
# ````````````````````````````````````````````````````````````````````
schedule:
  discoverall: null
#    when: '5 7 * * *'
  macwalk: null
#    when:
#      min: 20
  arpwalk: null
#    when:
 #     min: 50
  nbtwalk: null
#    when: '0 8,13,21 * * *'
  expire: null
#    when: '30 23 * * *'

# number of SNMP workers to run in parallel (in netdisco-backend).
# the default is twice the number of CPU cores. increase this if
# your system has few cores and the schedule is taking too long.
# ```````````````````````````````````````````````````````````````
#workers:
#  tasks: 'AUTO * 2'

# number of parallel DNS queries for node names
# `````````````````````````````````````````````
#dns:
#  max_outstanding: 50