CREATE TABLE netflow (
    type SYMBOL,
    sampler_address SYMBOL,
    src_addr SYMBOL,
    dst_addr SYMBOL,
    etype SYMBOL,
    proto SYMBOL,
    src_mac SYMBOL,
    dst_mac SYMBOL,
    next_hop SYMBOL,
    src_net SYMBOL,
    dst_net SYMBOL,
    vlan_id SYMBOL,
    bgp_next_hop SYMBOL,
    bgp_communities SYMBOL,
    as_path SYMBOL,
    mpls_ttl SYMBOL,
    mpls_label SYMBOL,
    mpls_ip SYMBOL,
    layer_stack SYMBOL,
    layer_size SYMBOL,
    ipv6_routing_header_addresses SYMBOL,
    time_received TIMESTAMP,
    time_flow_start TIMESTAMP,
    time_flow_end TIMESTAMP,
    sequence_num LONG,
    sampling_rate LONG,
    bytes LONG,
    packets LONG,
    src_port LONG,
    dst_port LONG,
    in_if LONG,
    out_if LONG,
    src_vlan LONG,
    dst_vlan LONG,
    ip_tos LONG,
    forwarding_status LONG,
    ip_ttl LONG,
    ip_flags LONG,
    tcp_flags LONG,
    icmp_type LONG,
    icmp_code LONG,
    ipv6_flow_label LONG,
    fragment_id LONG,
    fragment_offset LONG,
    src_as LONG,
    dst_as LONG,
    next_hop_as LONG,
    observation_domain_id LONG,
    observation_point_id LONG,
    ipv6_routing_header_seg_left LONG
) TIMESTAMP(time_received) PARTITION BY MONTH;

CREATE TABLE netflow_p95 (
    src_addr SYMBOL,
    dst_addr SYMBOL,
    dst_port LONG,
    p95_bytes DOUBLE,
    window_start TIMESTAMP,
    window_end TIMESTAMP
) TIMESTAMP(window_start) PARTITION BY MONTH;

CREATE TABLE netflow_top_apps (
    app_name SYMBOL,
    total_bytes LONG,
    total_packets LONG,
    window_start TIMESTAMP,
    window_end TIMESTAMP
) TIMESTAMP(window_start) PARTITION BY MONTH;