apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    strelka.service: logs
  name: logs
  namespace: strelka
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi